Orifice model for cavities, ACH output, PerfectGas twinhouse and bugfixes
open-ideas/IDEAS pull request #1219
Opened 2021-06-04 14:03 UTC by kldjonge

Several alterations were mistakenly left on on older branch. I cherry-picked, corrected and recommitted them here.

The alterations concern:

- The use of an orifice model for the 1-port implementation of the cavity in the internal wall
- Added ACH output to each zone
- Changed shielding conditions of Twinhouse O5 to more realistic values (will only influence the pressure driven airflow simulations)
- TwinHouse05 case with Air.PerfectGas as the medium to have a better comparison with specialized airflow simulation software CONTAM. (Also showcases the use of this medium for cases were naturally driven airflows are important)
- Bugfix in the Twinhouse heating schedule that loaded the wrong initialization temperature.

2021-06-04 14:32 UTC, Mathadon requested changes
@kldjonge I have revised the code and I have a few questions. Can you have another look at these?

2021-06-04 14:32 UTC, Mathadon commented on IDEAS/Examples/TwinHouses/BaseClasses/Ventilation/Vent_TTH_pressureNetwork_AirPerfectGass.mo
> +within IDEAS.Examples.TwinHouses.BaseClasses.Ventilation;
@kldjonge can you add documentation in the information section about why this class is needed? It sounds like you need a different Medium but you could have achieved that simply by redeclaring the Medium in the original model?

2021-06-04 14:32 UTC, Mathadon commented on IDEAS/Examples/TwinHouses/BuildingO5_Exp1_1Port_PerfectGass.mo
> +  "Model for simulation of experiment 1 for the O5 building"
We already have `IDEAS.Examples.TwinHouses.BuildingO5_Exp1` for `Model for simulation of experiment 1 for the O5 building`. Can you adjust the documentation such that it is clear what the purpose of this model is? Please change both this comment and add a note in the documentation section.

2021-06-04 14:32 UTC, Mathadon commented on IDEAS/Examples/TwinHouses/BuildingO5_Exp1_1Port_PerfectGass.mo
> +          "modelica://IDEAS/Resources/Scripts/Dymola/Examples/TwinHouses/BuildingO5_Exp1.mos"
The .mos file indicated in this line its the unit test for the model BuildingOO5_Exp1. Can you add a similar mos file for this model and adjust the path accordingly? Then this model is unit tested together with the others. I can add the reference results.

2021-06-04 14:32 UTC, Mathadon commented on IDEAS/Examples/TwinHouses/Interfaces/PartialTTHStructure_AirPerfectGass.mo
> +    redeclare each package Medium = Media.Specialized.Air.PerfectGas,
can't you simply extend the other model and adjust the Medium?

2021-06-07 10:09 UTC, kldjonge commented
While trying to solve the comments, I found other issues with the original implementation of the Air.PerfectGass variation.
Also I can't make redeclaring the medium package top-level work. In the structure model it seems like not all sub-level packages are redeclared triggering errors. 

To be clear, we used the model without Air.PerfectGass for the paper.

2021-06-07 10:37 UTC, Mathadon commented
@kldjonge do we need the PerfectGass variation in IDEAS if we did not use it for the paper? I see that you removed it, which is a valid solution for me!

2021-06-07 11:02 UTC, merged

2021-06-07 11:02 UTC, Mathadon commented
@kldjonge I already merged these changes. Are there any others you'd like to add?

2021-06-07 11:43 UTC, kldjonge commented
Should the CONTAM reference results be included for testing the airflows?

2021-06-07 11:45 UTC, Mathadon commented
It would indeed be useful to have a Modelica model that implements an airflow network and that also contains a CombiTimeTable with matching CONTAM results for intercomparison! We could then include a unit test or even asserts that verify whether the error compared to contam is within some bounds. Could you add such a model?

2021-06-07 15:41 UTC, kldjonge commented
Like this?

https://github.com/kldjonge/IDEAS/tree/1066_interzonal_KDJ

I noticed some deviations that aren't in the results generated in January though. E.g. In the W40.resDoor.m_flow, the dynamics are opposite but the steady state at the start is more or less correct, so changing the sign doesn't help in this case because then the whole graph is mirrored against the X-axis, and not around the 'center'

![image](https://user-images.githubusercontent.com/46526840/121048654-47a6fa00-c7b7-11eb-99c5-42f13c71458f.png)

[CONTAMTwinHouseO5.txt](https://github.com/open-ideas/IDEAS/files/6610297/CONTAMTwinHouseO5.txt)

2021-06-07 19:58 UTC, Mathadon commented
Yup, that's pretty much what I meant!

I'm getting different results than you though? 

<img width="1336" alt="image" src="https://user-images.githubusercontent.com/5970879/121080095-4687c400-c7db-11eb-9f0b-51fb359d4794.png">

The flow rates look like they're a factor two off. 

Possibly I made an error somewhere during refactoring :s

2021-06-07 20:23 UTC, Mathadon commented
Should the orifice exponent for doors be 0.5 or 0.65?

And what is the mass flow rate convention for the CONTAM results? Is the flow rate positive when leaving or entering the building?

2021-06-08 08:07 UTC, kldjonge commented
The exponent should be 0.5 and the discharge coefficient 0.78.
This can be changed but by default in CONTAM, positive flow is ambient to indoors.

2021-06-08 08:20 UTC, Mathadon commented
Ok the convention in Modelica is often the other way around.

I plotted some comparisons of a few signals. Are these errors in line with the errors that you had before?
<img width="1356" alt="image" src="https://user-images.githubusercontent.com/5970879/121149523-052aff00-c843-11eb-8d0a-4c654bca9143.png">
Possibly the errors changed because the CONTAM reference file uses outdated prescribed temperatures from an older IDEAS model?

2021-06-08 08:36 UTC, kldjonge commented
That could explain the differences indeed. Modelica seems to peak higher at sudden events. But like you said, the indoor temperatures are not the same anymore where in the paper I made sure the CONTAM simulations was done after the Modelica simulation and temperatures where the same.

To compare with the paper, the flow rates plotted are:

- For external walls: W1,W7,W10
- For Internal walls: W37,W39, W42
- The open doors (resDoor): W40, W41, W42

2021-06-08 08:41 UTC, kldjonge commented
The W10 results did fit much better though. (graph is is flipped here, units in m³/h)

![image](https://user-images.githubusercontent.com/46526840/121153126-175a6c80-c846-11eb-9acb-c0dd5564b3e9.png)